<?php
/**
 * Sidebar recently viewed or compared product block
 *
 * @var \Magento\Framework\View\Element\Template $block
 */

$isViewedUiComponent = $block->getData('uiComponent') == 'widget_recently_viewed';
$uiComponentScope = $isViewedUiComponent ? 'recentlyViewedProducts' : 'recentlyComparedProducts';
$pageSize = intval($block->getData('page_size'));

$jsLayout = [
    '*' => [
        'Magento_Ui/js/core/app' => [
            'components' => [
                $uiComponentScope => array_merge([
                    'component' => 'DeepFish_CatalogRecentlyWidget/js/view/recently-products',
                    'config' => [
                        'template' => 'DeepFish_CatalogRecentlyWidget/sidebar',
                        'dataSection' => $isViewedUiComponent ? 'recently_viewed_product' : 'recently_compared_product',
                        'pageSize' => $pageSize,
                        'showAttributes' => $block->getData('show_attributes'),
                        'showButtons' => $block->getData('show_buttons'),
                        'imageCode' => $isViewedUiComponent ?
                            'recently_viewed_products_images_names_widget' :
                            'recently_compared_products_images_names_widget'
                    ]
                ], $block->getData('jsLayout'))
            ]
        ]
    ]
];
?>
<?php if($pageSize > 0): ?>
    <div class="block recently hide" data-bind="scope: '<?= $uiComponentScope ?>'" data-role-preloader>
        <h2 data-bind="css: $element.parentElement.classList.toggle('hide', !recentlyProducts().count)">
            <?= __($isViewedUiComponent ? 'Recently Viewed Products' : 'Recently Compared Products') ?>
        </h2>
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
    <script type="text/x-magento-init">
        <?= \Zend_Json::encode($jsLayout) ?>
    </script>
<?php endif; ?>
