<?php
/**
 * Product list template
 *
 * @var \Magento\Catalog\Block\Product\ListProduct $block
 */

$jsLayout = [
    'Magento_Ui/js/core/app' => [
        'components' => [
            $block->getJsId() => $block->getJsLayout()
        ]
    ]
];
?>
<div data-mage-init='<?= \Zend_Json::encode($jsLayout) ?>' data-bind="scope: '<?= $block->getJsId() ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
