<?php
/**
 * Product list template
 *
 * @var \Magento\Catalog\Block\Product\ListProduct $block
 */

$baseBlockName = 'catalog.product.list';
if($block->getNameInLayout() != $baseBlockName) {
    $jsLayoutBlock = $block->getLayout()->getBlock($baseBlockName);
} else {
    $jsLayoutBlock = $block;
}

$jsLayout = $jsLayoutBlock->getData('jsLayout');
$jsLayout['Magento_Ui/js/core/app']['components']['productList']['config'] += $block->getData('jsLayoutConfig');
?>
<div data-mage-init='<?= \Zend_Json::encode($jsLayout) ?>'>
    <div data-bind="scope: 'productList'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
