<?php
/**
 * Header compare block
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="dropdown compare">
    <a href="#" class="action" data-bind="scope: 'compareProducts'">
        <span class="inner">
            <span class="label"><?= __('Compare') ?></span>
            <span class="count" data-bind="text: compareProducts().countCaption || '<?= __('0 items') ?>'"></span>
        </span>
    </a>
    <div class="dialog preloader" data-bind="scope: 'compareProducts'">
        <!-- ko if: compareProducts().count -->
            <a href="#" class="icon close" title="<?= __('Close') ?>"></a>
        <!-- /ko -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
