<?php
/**
 * Header compare block
 *
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Magento\Framework\View\Element\Template $block
 */

/** @var \Magento\Catalog\Helper\Product\Compare $compareHelper */
$compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);

/** @var \Magento\Framework\Data\Helper\PostHelper $postHelper */
$postHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
?>
<div class="dropdown compare">
    <a href="#" class="action" data-bind="scope: 'compareProducts'">
        <span class="inner">
            <span class="label"><?= __('Compare') ?></span>
            <span class="count" data-bind="text: compareProducts().countCaption || '<?= __('0 items') ?>'"></span>
        </span>
    </a>
    <div class="dialog" data-role="dropdown-dialog">
        <div data-bind="scope: 'compareProducts'">
            <!-- ko if: compareProducts().count -->
                <a href="#" class="icon close" title="<?= __('Close') ?>"></a>
                <div class="title"><?= __('Items to compare') ?></div>
                <!-- ko foreach: compareProducts().items -->
                    <div class="item">
                        <a href="#"
                           class="icon remove"
                           title="<?= __('Remove this item') ?>"
                           data-bind="attr: {'data-post': remove_url}">
                        </a>
                        <a class="name" data-bind="attr: {href: product_url, title: name}">
                            <!-- ko text: name --><!-- /ko -->
                        </a>
                    </div>
                <!-- /ko -->
                <div class="actions">
                    <a class="button" data-bind="attr: {'href': compareProducts().listUrl}">
                        <span><?= __('Compare') ?></span>
                    </a>
                    <a href="#"
                       class="clear"
                       data-post='<?= $postHelper->getPostData($compareHelper->getClearListUrl()) ?>'>
                        <?= __('Clear All') ?>
                    </a>
                </div>
            <!-- /ko -->
            <!-- ko ifnot: compareProducts().count -->
                <?= __('You have no items to compare.') ?>
            <!-- /ko -->
        </div>
    </div>
</div>
