<?php
/**
 * Product list
 *
 * @var \Magento\Catalog\Block\Product\AbstractProduct $block
 */

$type = $block->getData('type');
$items = $block->getItems();
if(!is_array($items)) {
    $items = $items->getData();
}
?>
<?php if(count($items)): ?>
    <div class="<?= $block->getJsId() ?>">
        <?php if($type == 'related'): ?>
            <h2>
                <span><?= __('Related') ?></span>
                <?= __('Products') ?>
            </h2>
        <?php elseif($type == 'upsell'): ?>
            <h2>
                <span><?= __('You may also be') ?></span>
                <?= __('Interested in the following products') ?>
            </h2>
        <?php endif; ?>

        <?php include($block->getTemplateFile('Magento_Catalog::product/list.phtml')); ?>
    </div>
<?php endif; ?>
