<?php
/**
 * Header wishlist block
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<div class="dropdown wishlist">
    <a href="#" class="action" data-bind="scope: 'wishlist'">
        <span class="inner">
            <span class="label"><?= __('Wishlist') ?></span>
            <span class="count" data-bind="text: wishlist().counter || '<?= __('0 items') ?>'"></span>
        </span>
    </a>
    <div class="dialog" data-bind="scope: 'wishlist'" data-role-dropdown-dialog data-role-preloader>
        <!-- ko if: wishlist().counter -->
            <a href="#" class="icon close" title="<?= __('Close') ?>"></a>
        <!-- /ko -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
</div>
