<?php
/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php
switch ($block->getShowPart()):
    case 'welcome': ?>
        <div class="welcome" data-bind="scope: 'customer'">
            <p data-bind="text: customer().fullname ?
                '<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>'.replace('%1', customer().fullname) :
                '<?= $block->escapeHtmlAttr($welcomeMessage) ?>'">
            </p>
            <?=$block->getBlockHtml('header.additional')?>
        </div>
    <?php break; ?>
<?php endswitch; ?>
