<?php
/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php
switch ($block->getShowPart()):
    case 'welcome': ?>
        <div data-mage-init='<?= $block->getJsLayout() ?>' class="welcome">
            <p data-bind="scope: 'customer'">
                <!-- ko if: customer().fullname  -->
                <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1',
                customer().fullname)">
                </span>
                <!-- /ko -->
                <!-- ko ifnot: customer().fullname  -->
                <span data-bind='html:"<?= $block->escapeHtmlAttr($welcomeMessage) ?>"'></span>
                <?= $block->getBlockHtml('header.additional') ?>
                <!-- /ko -->
            </p>
        </div>
    <?php break; ?>
<?php endswitch; ?>
