<?php
/** @var \Magento\Store\Block\Switcher $block */

/** @var \Magento\Framework\Data\Helper\PostHelper $helper */
$helper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
?>
<?php if (count($block->getStores()) > 1): ?>
    <div class="switcher">
        <a class="action" title="Language" href="#"><?= $block->escapeHtml($block->getStoreCode()) ?></a>
            <ul>
                <?php foreach ($block->getStores() as $_lang): ?>
                     <li>
                        <a href="#" data-post='<?=$block->getTargetStorePostData($_lang)?>'
                           <?=($_lang->getId() == $block->getCurrentStoreId() ? "class=\"selected\"" : "")?>>
                            <?= $block->escapeHtml($_lang->getName()) ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
    </div>
<?php endif; ?>
