<?php
/**
 * Header minicart block
 *
 * @var \Magento\Checkout\Block\Cart\Sidebar $block
 */

$jsLayout = \Zend_Json::decode($block->getJsLayout());
$jsConfig = $block->getConfig();

$jsLayout['components']['minicart_content']['config'] += [
    'checkoutUrl' => $jsConfig['checkoutUrl'],
    'shoppingCartUrl' => $jsConfig['shoppingCartUrl'],
    'updateItemQtyUrl' => $jsConfig['updateItemQtyUrl'],
    'maxItemsToDisplay' => $jsConfig['maxItemsToDisplay']
];
?>
<div class="dropdown minicart"
     data-mage-init='<?= \Zend_Json::encode(['Magento_Ui/js/core/app' => $jsLayout]) ?>'>
    <a href="<?= $block->getShoppingCartUrl() ?>"
       class="action<?php if(!$block->getIsNeedToDisplaySideBar()): ?> no-arrow<?php endif; ?>"
       data-bind="scope: 'minicart_content'">
        <span class="inner">
            <span class="label"><?= __('My Cart') ?></span>
            <span class="count" data-bind="text: cart().summary_count == 1 ? '<?= __('1 item') ?>' :
                '<?= __('%1 items') ?>'.replace('%1', cart().summary_count || 0)">
            </span>
        </span>
    </a>
    <?php if($block->getIsNeedToDisplaySideBar()): ?>
        <div class="dialog" data-role="dropdown-dialog">
            <div data-bind="scope: 'minicart_content'" data-role="preloader">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php endif; ?>
</div>
